# Generated by Django 5.1.1 on 2025-04-05 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_lookup', '0002_garage_delete_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='garage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='garage',
            name='plate_number',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='garage',
            name='registration',
        ),
    ]
