# Generated by Django 5.1.7 on 2025-04-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_lookup', '0003_alter_garage_unique_together_garage_plate_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Garage',
        ),
    ]
