# Generated by Django 5.1.7 on 2025-04-18 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_lookup', '0006_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedcar',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedcar',
            name='user',
        ),
        migrations.CreateModel(
            name='CarsInGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.CharField(max_length=10)),
                ('linkeduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('linkeduser', 'regnum')},
            },
        ),
        migrations.CreateModel(
            name='SavedChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.CharField(max_length=20)),
                ('carchecklist', models.JSONField(default=dict)),
                ('linkeduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='SavedCar',
        ),
    ]
