# Generated by Django 5.1.7 on 2025-05-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
